config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :users, only: [:new, :create] do
    collection do
      get :login
      post :do_login
      delete :logout
    end
  end

  resource :user, only: [:edit, :update, :destroy]
  resources :counters do
    member do
      get :fullscreen
      post :reset
    end
    resources :collaborations, only: [:index, :create, :destroy]
  end

  namespace :api do
    resources :users, only: [:none] do
      collection do
        post :token
      end
    end

    resources :counters, only: [:index, :show] do
      member do
        post :reset
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :counters, dependent: :destroy
  has_many :collaborations, dependent: :destroy
  has_many :collaborator_counters, through: :collaborations, source: :counter
  validates :name, presence: true, uniqueness: true
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  skip_before_action :authenticate_user, only: :token

  def token
    @user = User.find_by(name: params[:user][:name])&.authenticate(params[:user][:password])
    render json: { error: 'Invalid username or password' }, status: 401 and return if @user.blank?

    render json: { token: JsonWebToken.encode(user_id: @user.id) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user, only: [:edit, :update, :destroy, :logout]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.persisted?
      flash[:success] = 'Your user account was created successfully'
      redirect_to root_url
    else
      flash[:error] = "Failed to create your user account: #{@user.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit; end

  def update
    if current_user.authenticate(params[:user][:old_password])
      if current_user.update(user_params)
        flash[:success] = 'Your information has been updated successfully'
      else
        flash[:error] = "Failed to update your information: #{current_user.errors.full_messages.join(', ')}}"
      end
    else
      flash[:error] = "Failed to update your information: Old password is invalid"
    end
    render :edit
  end

  def destroy
    if current_user.destroy
      reset_session
      flash[:success] = 'Your user account has been deleted successfully'
    else
      flash[:error] = 'Failed to delete your user account'
    end
    redirect_to root_url
  end

  def login
    @user = User.new
  end

  def do_login
    @user = User.find_by(name: params[:user][:name])&.authenticate(params[:user][:password])
    if @user
      session[:current_user_id] = @user.id
      flash[:success] = 'Login successful'
      redirect_to root_url
    else
      flash[:error] = 'Login failed: Wrong username or password'
      render :login
    end
  end

  def logout
    reset_session
    flash[:success] = 'Logout successful'
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/views/users/edit.html.haml
%h1 Change your password

.col-8.mr-auto.ml-auto
  .card
    .card-body
      = form_with model: current_user, class: 'form-horizontal', local: true do |f|
        .form-group
          = f.label :name, 'Username'
          = f.text_field :name, class: 'form-control-plaintext', id: 'userName', readonly: true
        .form-group
          = f.label :old_password, 'Old password'
          = f.password_field :old_password, class: 'form-control', id: 'userOldPassword', required: true
        .form-group
          = f.label :password, 'New password'
          = f.password_field :password, class: 'form-control', id: 'userPassword', required: true
        .form-group
          = f.label :password_confirmation, 'Confirm new password'
          = f.password_field :password_confirmation, class: 'form-control', id: 'userPasswordConfirmation', required: true
        .form-group
          = f.submit 'Save changes', class: 'btn btn-primary d-inline-block'
          %a.btn.btn-danger.d-inline-block{ href: user_path, data: { method: :delete, confirm: 'This will irreversibly delete your account and all associated data. Are you sure you want to continue?' }, rel: :nofollow } Delete account

app/views/users/login.html.haml
%h1 Login

.col-8.mr-auto.ml-auto
  .card
    .card-body
      = form_with model: @user, scope: :user, url: do_login_users_path, class: 'form-horizontal', local: true do |f|
        .form-group
          = f.label :name, 'Username'
          = f.text_field :name, class: 'form-control', id: 'userName', required: true
        .form-group
          = f.label :password, 'Password'
          = f.password_field :password, class: 'form-control', id: 'userPassword', required: true
        .form-group
          = f.submit 'Login', class: 'btn btn-primary'

app/views/users/new.html.haml
%h1 Register a new user account

.col-8.mr-auto.ml-auto
  .card
    .card-body
      = form_with model: @user, scope: :user, class: 'form-horizontal', local: true do |f|
        .form-group
          = f.label :name, 'Username'
          = f.text_field :name, class: 'form-control', id: 'userName', required: true
        .form-group
          = f.label :password, 'Password'
          = f.password_field :password, class: 'form-control', id: 'userPassword', required: true
        .form-group
          = f.label :password_confirmation, 'Confirm password'
          = f.password_field :password_confirmation, class: 'form-control', id: 'userPasswordConfirmation', required: true
        .form-group
          = f.submit 'Register', class: 'btn btn-primary'