config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :users, only: [:new, :create] do
    collection do
      get :login
      post :do_login
      delete :logout
    end
  end

  resource :user, only: [:edit, :update, :destroy]
  resources :counters do
    member do
      get :fullscreen
      post :reset
    end
    resources :collaborations, only: [:index, :create, :destroy]
  end

  namespace :api do
    resources :users, only: [:none] do
      collection do
        post :token
      end
    end

    resources :counters, only: [:index, :show] do
      member do
        post :reset
      end
    end
  end
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :user
  belongs_to :counter
  validates :counter_id, uniqueness: { scope: :user_id }
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :require_current_user, only: [:index, :create, :destroy]
  before_action :find_counter, only: [:index, :create, :destroy]
  before_action :find_collaboration, only: [:destroy]
  def index
    @collaborations = @counter.collaborations.includes(:user)
    @available_users = User.where.not(id: Array.wrap(@collaborations.pluck(:user_id)) + [current_user.id])
    @new_collaboration = @counter.collaborations.build
  end

  def create
    user = User.find(params[:collaboration][:user_id])
    @collaboration = @counter.collaborations.create(user: user)
    if @collaboration.persisted?
      flash[:success] = 'New collaborator added successfully'
    else
      flash[:error] = "Could not add new collaborator: #{@collaboration.errors.full_messages.join(', ')}"
    end
    redirect_to counter_collaborations_url(@counter)
  end

  def destroy
    if @collaboration.destroy
      flash[:success] = 'Collaborator deleted successfully'
    else
      flash[:error] = 'Could not delete collaborator'
    end
    redirect_to counter_collaborations_url(@counter)
  end

  private

  def find_counter
    @counter = current_user.counters.find(params[:counter_id])
  end

  def find_collaboration
    @collaboration = @counter.collaborations.find(params[:id])
  end
end

app/views/collaborations/index.html.haml
%h1 Collaborators for counter #{@counter.name}
- if @collaborations.blank?
  .alert.alert-info No collaborators yet
- else
  %table.table.table-striped
    %thead
      %tr
        %th{ scope: 'col' } Name
        %th{ scope: 'col' }
    %tbody
      - @collaborations.each do |collaboration|
        %tr
          %td= collaboration.user.name
          %td
            %a.btn.btn-danger{ href: counter_collaboration_path(@counter, collaboration), data: { method: :delete, confirm: 'Are you sure you want to delete this collaborator?' } } Delete
= form_with(model: @new_collaboration, url: counter_collaborations_path(@counter), local: true) do |f|
  .form-row
    .col-3
      = f.select :user_id, options_from_collection_for_select(@available_users, :id, :name), {}, id: 'collaborationUserId', title: 'Select new collaborator...', data: { live_search: :true, width: '100%' }, required: true
    .col-2
      = f.submit 'Add collaborator', class: 'btn btn-success'